### PR TITLE
Created a sample extension to share using intents.

### PR DESCRIPTION
**Pull request by scr**
We should really refactor some of this stuff - I couldn't figure out a way to do the extension without actually including the shim and injecting it into all pages :(

### CODE REVIEW

**Comment by PaulKinlan** [comment]
That is the way we need to do it.  The share extension in the tools directory does this too.

**Comment by scr** [comment]
Paul.  I played with your extension a little.  FWIW, by initiating the intent from the content_script, it avoids the popup.  However, I haven't figured out how to get twitter/google+ working again.

Please have a look.  I'll try to keep tinkering, but I'm on vacation now...

**Comment by scr** [comment]
Did I close this?  I didn't mean to...  Can we get this merged?

**Comment by scr** [comment]
You know what - for some reason after reopening it's not getting the latest changes to fix twitter.  Let me close again and make a new pull request :)

**Pull request closed without merging**
