### PR TITLE
Pull this

### PR DESCRIPTION
**Pull request by nico**
Hi Paul,

you said "fix spelling plz" to someone on reddit. I took a stab at that, in case that redditor doesn't.

Nico

ps: In vim, it's `:set spell`, ]s to go to the next word, z= to get suggestions, zg to mark the current word as "good" – see `:help spell`. Other editors can spell check, too.

### CODE REVIEW

**Comment by PaulKinlan** [comment]
Sweet. And thanks for the tip too...  will pull asap.
On Aug 7, 2011 9:58 PM, "nico" <
reply@reply.github.com>
wrote:

**Comment by nico** [comment]
Thanks! Looks like this hasn't reached webintents.org yet – do you have to restart some server?

**Comment by PaulKinlan** [comment]
I haven't fixed it yet.
On Aug 13, 2011 10:09 PM, "nico" <
reply@reply.github.com>
wrote:

**Comment by PaulKinlan** [comment]
when I say fixed, I mean pushed live, I am working on another branch at the moment.

**Pull request merged**
